[package]
name = "breakspan-otlp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
breakspan-core.workspace = true
breakspan-store.workspace = true
opentelemetry-proto.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true

[lints]
workspace = true
